services:
  elasticsearch:
    image: elasticsearch:8.18.4
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false

  kibana:
    image: kibana:8.18.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    command: filebeat -e --strict.perms=false
    volumes:
      - ./logs:/src/logs
    depends_on:
      - elasticsearch
      - kibana

  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    volumes:
      - ./logs:/server/dist/logs

volumes:
  elasticsearch_data:
    driver: local

  grafana-data:
